### ISSUE TITLE
Module version mismatch. Expected 48, got 47 while running node app.js

### ISSUE THREAD

**Issue by ashu1994** [IBM-Blockchain/car-lease-demo#100]
When i am runnning node app.js by my own , i am getting this issue. I thought that its the node version issues so i used 6.9.5 , 6.2.1, 6.1.0 but in all three i am getting this issue. Can i get any help

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/akshit.jain/blockchainexamples/car-lease-demo/node_modules/grpc/src/node/src/grpc
_extension.js:38:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by 14gracel** [comment]
Can you please give more details about your environment? Which OS are you running, how are you trying to run the demo, etc
