### ISSUE TITLE
Not compatible with node v8.1.3?

### ISSUE THREAD

**Issue by snowwolf007cn** [IBM-Blockchain/car-lease-demo#119]
1 warning and 1 error generated.
make: *** [Release/obj.target/grpc_node/src/node/ext/call.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/zhangzhi/workspace/car-lease-demo/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.1.3/bin/node" "/Users/zhangzhi/workspace/car-lease-demo/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/8.1.3/bin/node /Users/zhangzhi/workspace/car-lease-demo/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.1.3/bin/node" "/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc
node-pre-gyp ERR! node -v v8.1.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/8.1.3/bin/node /Users/zhangzhi/workspace/car-lease-demo/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/zhangzhi/workspace/car-lease-demo/node_modules/grpc/src/node/extension_binary' (1)
npm WARN Car-Lease-Demo@0.7.3 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangzhi/.npm/_logs/2017-07-25T02_12_25_531Z-debug.log

**Comment by kavinaravind** [comment]
If you look at the pre-reqs for installing locally, it says NodeJS v6.x. I used nvm to install v6.10 and was able to call npm install with no issues.
