### ISSUE TITLE
application not running after "npm i" done

### ISSUE THREAD

**Issue by zamrokk** [IBM-Blockchain/car-lease-demo#18]
I just pulled the code,
when launching : node app.js 
after a "npm i"
I got this error :

/Users/benjaminfuentes/git/car-lease-demo/node_modules/require-reload/reload.js:16
        throw e;
        ^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.<anonymous> (/Users/benjaminfuentes/git/car-lease-demo/Server_Side/configurations/configuration.js:10:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at reloadCtx (/Users/benjaminfuentes/git/car-lease-demo/node_modules/require-reload/reload.js:11:16)
    at Object.<anonymous> (/Users/benjaminfuentes/git/car-lease-demo/Server_Side/blockchain/blocks/CRUD/read.js:5:18)

**Comment by jpayne23** [comment]
Hi zamrokk,

This is an error retrieving an environment variable from bluemix, because the demo was built specfically for the blockchain service on bluemix. Unfortunately this service is not working right now so it is not possible to deploy the demo to bluemix.

Because of this we are working on making the demo a lot easier to run locally and we will have an updated demo shortly (along with install instructions) when the bluemix service resumes, we are waiting so we can make sure the demo still works on bluemix.

Thanks

**Comment by zamrokk** [comment]
Ok 

thank you for the quick answer   :D 

Waiting for it  👯
